### ISSUE TITLE
Feature wish/question: swipe remote app?

### ISSUE THREAD

**Issue by houser42** [DeutscheMark/homebridge-kodi#10]
Thanks for this plugin. Very useful!
Q: Is it possible to build a remote with swipe GUI for Kodi in the Home app similar or identical
to the one that the Apple TV has? It seems like the new TV functionality could possibly be used?At least in theory? Just curious. Many thanks!

**Comment by DeutscheMark** [comment]
Hi, the new TV accessory with remote is already available through this plugin. Just add "television" > "controls" / "tv" to the config and add some "menuitems" / "channels" in it. You will then get a remote in the control center widget. Unfortunately there is no functionality like swipe available like for the Apple TV. That seems to be exclusive to them.

**Comment by houser42** [comment]
Thanks @DeutscheMark  !
That was a very good thing to know and I must confess a severe case of RTFM ;)
It was already there in the Control Centre, I just was not aware of that it was.
So no way to get at it from the Home app at this point? 
Swipe would be better obviously. 
There does seems to be an obvious opportunity to do decent rudimentary control ov various devices via this path for Apple. Hope they pursue it...
Many thanks again, this is all already very useful!
