### ISSUE TITLE
Two TV accessories from different plugins

### ISSUE THREAD

**Issue by nikoladuke** [DeutscheMark/homebridge-kodi#12]
Hi All,

I am using this plugin together with homebridge-broadlink-rm-tv v4.0.5.
Due to the limitation of the Homekit only one TV remote is shown in Control Centre.
Is it possible to have TV remotes from both plugins?

The support for this functionality in Homebridge is described here:
https://github.com/nfarina/homebridge/issues/2184

Thanks!

**Comment by DeutscheMark** [comment]
In fact I wasn't aware of that limitation, but I could replicate the problem with another TV accessory plugin in the same Homebridge instance. I'll look into it soon and maybe implement a fix in one the next versions. In the meantime you could add another Homebridge instance and seperate the two plugins to avoid it.

**Comment by DeutscheMark** [comment]
v1.0.1 released that fixes the issues with external TV accessories.
