### ISSUE TITLE
Polling interval

### ISSUE THREAD

**Issue by i3laze** [DeutscheMark/homebridge-kodi#4]
Seems polling variable used exactly for reporting playback progress to HomeKit and HB log.
Other plugin activities are trigger-based, which is instant and great!

What if I’m not interested in spamming my HomeBridge log at all?
I suggest handling “polling: 0” as no polling and status=100%.

**Comment by DeutscheMark** [comment]
It‘s also used for updating the accessories. If you set polling to zero it wouldn’t update at all. Right now it‘d produce an error so I fix that one in the next bigger version. I will also add a debug setting in the config that disables the logs by default.
