### ISSUE TITLE
Pause and automations 

### ISSUE THREAD

**Issue by i3laze** [DeutscheMark/homebridge-kodi#7]
Just wondering:
I’ve added a Pause switch to HomeKit automation with an action to toggle it On..
Hitting such automation while Pause toggle is already On unpauses playback :(
Seems like a false activation/bug. Is that so?

Currently I have to add a condition “while Playback is off” via Eve.app as a workaround.

**Comment by DeutscheMark** [comment]
Thanks for posting this issue.
It's indeed a bug as the switch does currently just toggle the play status and not really setting it.

I already changed the method for the play and pause switches to correctly send the commands to Kodi so automations should work fine then.

I will release the fix soon with 0.3.0, but it's not quite ready yet.

**Comment by DeutscheMark** [comment]
Should be fixed now with v0.3.0.

**Comment by i3laze** [comment]
Great job,
Will give it a try.. after holidays :)
