### ISSUE TITLE
Playing Status

### ISSUE THREAD

**Issue by IRONROCK20** [DeutscheMark/homebridge-kodi#8]
It could be cool, if possible, have a sensor of the playing status for light automation.
I’m using http-advancedaccessory but I’d like to use this branch because it’s fantastic.
Thanks!

**Comment by DeutscheMark** [comment]
Hi, thanks for asking. If I understand you correctly exactly this is already possible with the available accessories. Either you just use the default lightbulb accessory (minimal config) or use the playerPlay (or playerPause for the opposite behavior) accessory for this. With both of the accessories you can set the play status as trigger to do what should happen when playing or pausing. If you need further help doing thing I can add some screenshots for understanding.

**Comment by i3laze** [comment]
Indeed, plugin works great with light automations:
If Player on, light off
If Pause on, light on
If door/light on, Pause on
etc.

However there’s a small [bug](https://github.com/DeutscheMark/homebridge-kodi/issues/7) with fix pending in v0.3.0.

**Comment by DeutscheMark** [comment]
The mentioned bug should be fixed now with v0.3.0.
